In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("cbb_data.csv")

# Clean column headers (fixes hidden newlines/spaces)
df.columns = (
    df.columns
      .str.replace(r"\s+", " ", regex=True)
      .str.strip()
)

# Drop Unnamed columns safely
df = df.loc[:, ~df.columns.str.startswith("Unnamed:")].copy()

In [3]:
# Keep signed spread for favorite filtering
df["CLOSING SPREAD"] = pd.to_numeric(df["CLOSING SPREAD"], errors="coerce")

# Use ABS spread ONLY for bucketing
df["SPREAD_ABS"] = df["CLOSING SPREAD"].abs()

# Points + outcome columns
df["F"] = pd.to_numeric(df["F"], errors="coerce")
df["Team W/L (1/0)"] = pd.to_numeric(df["Team W/L (1/0)"], errors="coerce")
df["Team ML + Opp Team Over Win/Loss (1/0)"] = pd.to_numeric(
    df["Team ML + Opp Team Over Win/Loss (1/0)"], errors="coerce"
)

print("Min/Max closing spread:", df["CLOSING SPREAD"].min(), df["CLOSING SPREAD"].max())
print("Favorite rows (spread < 0):", (df["CLOSING SPREAD"] < 0).sum())

Min/Max closing spread: -49.5 49.5
Favorite rows (spread < 0): 5761

In [4]:
df.head()

,BIGDATABALL DATASET,GAME-ID,DATE,TEAM,F,OPENING TOTAL,CLOSING SPREAD,CLOSING TOTAL,CLOSING MONEYLINE,PROJ TEAM TOTAL (CLOSE),Team W/L (1/0),Team Over/Under Proj Team Total (1/0),Team ML + Opp Team Over Win/Loss (1/0),SPREAD_ABS
0,NCAAB 2024-2025 Regular Season,401706962,11/4/2024,Howard Bison,57,152.5,28.5,156.5,2200,64,0,0,0.0,28.5
1,NCAAB 2024-2025 Regular Season,401706962,11/4/2024,Kansas Jayhawks,87,152.5,-28.5,156.5,-8000,92.5,1,0,0.0,28.5
2,NCAAB 2024-2025 Regular Season,401719228,11/4/2024,UNC Asheville Bulldogs,54,162.5,28.5,163.5,3000,67.5,0,0,0.0,28.5
3,NCAAB 2024-2025 Regular Season,401719228,11/4/2024,Alabama Crimson Tide,110,162.5,-28.5,163.5,-10000,96,1,1,0.0,28.5
4,NCAAB 2024-2025 Regular Season,401706926,11/4/2024,Jackson State Tigers,40,136.5,36.5,136.5,2000,50,0,0,0.0,36.5

In [5]:
spread_col = "SPREAD_ABS"
points_col = "F"

# Use the absolute spread for bucketing; keep `CLOSING SPREAD` signed for favorite filtering
df[spread_col] = pd.to_numeric(df[spread_col], errors="coerce")
df["points_bucket"] = pd.qcut(df[points_col].rank(method="first"), 3, labels=["low","mid","high"])

In [6]:
spread_bins = [1, 5, 10, np.inf]
spread_labels = ["1–5", "5–10", "10+"]

df["spread_bucket"] = pd.cut(
    df[spread_col] ,
    bins=spread_bins,
    labels=spread_labels,
    right=False
)

In [7]:
df["points_bucket"] = pd.qcut(
    df[points_col].rank(method="first"),
    q=3,
    labels=["low", "mid", "high"]
)

In [8]:
bucket_counts = (
    df
    .groupby(["spread_bucket", "points_bucket"])
    .size()
    .unstack(fill_value=0)
)

print(bucket_counts)

points_bucket   low   mid  high
spread_bucket
1–5            1414  1786  1304
5–10           1174  1342  1165
10+            1165   940  1234

In [9]:
cuts, bins = pd.qcut(
    df["F"],
    q=3,
    retbins=True
)

print(bins)

[ 19.  67.  78. 143.]

Now checking to see if the favorites have won (given favourites have won what is the probability that the underdogs score the over)

In [10]:
df["CLOSING MONEYLINE"] = pd.to_numeric(df["CLOSING MONEYLINE"], errors="coerce")
df["Team W/L (1/0)"] = pd.to_numeric(df["Team W/L (1/0)"], errors="coerce")

df_fav = df[df["CLOSING MONEYLINE"] < 0].copy()

p_fav_win = df_fav["Team W/L (1/0)"].mean()
n_games = len(df_fav)

print(f"Probability favorite wins: {p_fav_win:.4f} (n={n_games})")

Probability favorite wins: 0.7253 (n=5988)

In [11]:
df_fav_win = df_fav[df_fav["Team W/L (1/0)"] == 1].copy()

# Ensure the parlay indicator is numeric
df_fav["Team ML + Opp Team Over Win/Loss (1/0)"] = pd.to_numeric(
    df_fav["Team ML + Opp Team Over Win/Loss (1/0)"], errors="coerce"
)

# Joint probability: favorite won AND opponent went over
p_joint = df_fav["Team ML + Opp Team Over Win/Loss (1/0)"].mean()

# Conditional probability: P(opponent over | favorite wins) = P(fav win AND opp over) / P(fav win)
p_opp_over_given_fav_win = p_joint / p_fav_win

n_cond = len(df_fav_win)
print(f"P(opp over | favorite wins) = {p_opp_over_given_fav_win:.4f} (n where fav won={n_cond})")

P(opp over | favorite wins) = 0.3990 (n where fav won=4343)

This is overall now for each bucket

In [12]:
# ensure numeric (safe even if already done)
df_fav["Team W/L (1/0)"] = pd.to_numeric(df_fav["Team W/L (1/0)"], errors="coerce")
df_fav["Team ML + Opp Team Over Win/Loss (1/0)"] = pd.to_numeric(
    df_fav["Team ML + Opp Team Over Win/Loss (1/0)"], errors="coerce"
)

# P(Favorite wins) per bucket
p_fav_win_bucket = (
    df_fav
    .groupby(["spread_bucket", "points_bucket"])["Team W/L (1/0)"]
    .mean()
)

# P(Favorite wins AND Opponent over) per bucket
p_joint_bucket = (
    df_fav
    .groupby(["spread_bucket", "points_bucket"])["Team ML + Opp Team Over Win/Loss (1/0)"]
    .mean()
)

# Conditional probability per bucket
p_opp_over_given_fav_win = (p_joint_bucket / p_fav_win_bucket).unstack()

# Sample size: games where favorite WON in each bucket
n_fav_win_bucket = (
    df_fav[df_fav["Team W/L (1/0)"] == 1]
    .groupby(["spread_bucket", "points_bucket"])
    .size()
    .unstack(fill_value=0)
)

# Pretty table: prob (n)
result = (
    p_opp_over_given_fav_win.round(3).astype(str)
    + " ("
    + n_fav_win_bucket.astype(str)
    + ")"
)

print("\nP(Underdog Over | Favorite Wins) by bucket:")
print(result)

P(Underdog Over | Favorite Wins) by bucket:
points_bucket          low          mid          high
spread_bucket
1–5            0.018 (221)  0.215 (583)   0.609 (609)
5–10           0.026 (155)  0.223 (512)   0.564 (713)
10+            0.121 (116)  0.375 (405)  0.531 (1027)

In [13]:
df_b = df[df["CLOSING SPREAD"] < 0].copy()
df_b = df_b.dropna(subset=["spread_bucket"])

df_b["Team W/L (1/0)"] = pd.to_numeric(df_b["Team W/L (1/0)"], errors="coerce")
df_b["Team ML + Opp Team Over Win/Loss (1/0)"] = pd.to_numeric(
    df_b["Team ML + Opp Team Over Win/Loss (1/0)"], errors="coerce"
)

b = (df_b["spread_bucket"]=="1–5") & (df_b["points_bucket"]=="low")

p_fav = df_b.loc[b, "Team W/L (1/0)"].mean()
p_joint = df_b.loc[b, "Team ML + Opp Team Over Win/Loss (1/0)"].mean()
ratio = p_joint / p_fav if (p_fav and not np.isnan(p_fav)) else np.nan

print("p_fav:", p_fav)
print("p_joint:", p_joint)
print("ratio:", ratio)
print("n rows in bucket:", b.sum())
print("n fav wins in bucket:", (df_b.loc[b, "Team W/L (1/0)"] == 1).sum())

p_fav: 0.3312
p_joint: 0.00641025641025641
ratio: 0.01935463891985631
n rows in bucket: 625
n fav wins in bucket: 207

In [14]:
# 1) how many favorite rows exist BEFORE dropping NaNs?
df_b0 = df[df["CLOSING SPREAD"] < 0].copy()
print("Favorite rows before dropna:", len(df_b0))

# 2) do the bucket columns exist?
print("Has spread_bucket:", "spread_bucket" in df_b0.columns)
print("Has points_bucket:", "points_bucket" in df_b0.columns)

# 3) if they exist, what's the NaN rate?
if "spread_bucket" in df_b0.columns and "points_bucket" in df_b0.columns:
    print("spread_bucket NA rate:", df_b0["spread_bucket"].isna().mean())
    print("points_bucket NA rate:", df_b0["points_bucket"].isna().mean())

# 4) show a few spreads to confirm the filter is sane
print(df_b0[["CLOSING SPREAD"]].head(10))

Favorite rows before dropna: 5761
Has spread_bucket: True
Has points_bucket: True
spread_bucket NA rate: 0.0
points_bucket NA rate: 0.0
    CLOSING SPREAD
1            -28.5
3            -28.5
5            -36.5
7            -46.5
9             -6.5
11           -32.5
13           -27.5
15           -36.5
17           -29.5
18            -6.5

In [15]:
df_bucket = df_b.dropna(subset=["spread_bucket","points_bucket"]).copy()

fav_wins = (
    df_bucket[df_bucket["Team W/L (1/0)"] == 1]
    .groupby(["spread_bucket","points_bucket"])
    .size()
    .unstack(fill_value=0)
)

fav_win_opp_over = (
    df_bucket[df_bucket["Team ML + Opp Team Over Win/Loss (1/0)"] == 1]
    .groupby(["spread_bucket","points_bucket"])
    .size()
    .unstack(fill_value=0)
)

print("Fav wins (denominator):")
print(fav_wins)

print("\nFav win + opp over (numerator):")
print(fav_win_opp_over)

print("\nConditional probability:")
print((fav_win_opp_over / fav_wins).replace([np.inf, -np.inf], np.nan))

Fav wins (denominator):
points_bucket  low  mid  high
spread_bucket
1–5            207  541   556
5–10           155  512   713
10+            116  405  1028

Fav win + opp over (numerator):
points_bucket  low  mid  high
spread_bucket
1–5              4  121   342
5–10             4  114   402
10+             14  152   546

Conditional probability:
points_bucket       low       mid      high
spread_bucket
1–5            0.019324  0.223660  0.615108
5–10           0.025806  0.222656  0.563815
10+            0.120690  0.375309  0.531128

In [16]:
df_b = df_fav.dropna(subset=["spread_bucket","points_bucket"]).copy()

df_b["Team Over/Under Proj Team Total (1/0)"] = pd.to_numeric(
    df_b["Team Over/Under Proj Team Total (1/0)"], errors="coerce"
)

# Under-dog wins = favorite losses
df_udog_win_b = df_b[df_b["Team W/L (1/0)"] == 0].copy()

prob_bucket = (
    df_udog_win_b
    .groupby(["spread_bucket","points_bucket"])["Team Over/Under Proj Team Total (1/0)"]
    .mean()
    .unstack()
)

n_bucket = (
    df_udog_win_b
    .groupby(["spread_bucket","points_bucket"])
    .size()
    .unstack(fill_value=0)
)

result = prob_bucket.round(3).astype(str) + " (" + n_bucket.astype(str) + ")"
print(result)

points_bucket          low          mid         high
spread_bucket
1–5            0.013 (466)  0.336 (432)  0.904 (167)
5–10           0.005 (191)   0.24 (192)   0.792 (77)
10+               0.0 (42)   0.038 (53)    0.68 (25)

In [17]:
print("this is a sanity check, both numbers should be the same")
print("Total underdog wins:", (df_fav["Team W/L (1/0)"] == 0).sum())
print("Sum of bucket underdog wins:", n_bucket.values.sum())

this is a sanity check, both numbers should be the same
Total underdog wins: 1645
Sum of bucket underdog wins: 1645

In [18]:
pd.set_option("display.max_rows", 300)   # or None for all rows
pd.set_option("display.max_columns", None)

# Favorites only
df_fav = df[df["CLOSING SPREAD"] < 0].copy()

# Filter: spread bucket 1–5, points low, favorite wins
mask = (
    (df_fav["spread_bucket"] == "1–5") &
    (df_fav["points_bucket"] == "low") &
    (df_fav["Team W/L (1/0)"] == 1)
)

# Show the column headers (all column names)
print(df_fav.columns.tolist())

# Show all matching rows (or cap with head if you want)
display(df_fav.loc[mask])          # shows all (Jupyter may still preview)
print("Rows matched:", mask.sum())

# If you specifically want the first 207 rows:
# display(df_fav.loc[mask].head(207))

['BIGDATABALL DATASET', 'GAME-ID', 'DATE', 'TEAM', 'F', 'OPENING TOTAL', 'CLOSING SPREAD', 'CLOSING TOTAL', 'CLOSING MONEYLINE', 'PROJ TEAM TOTAL (CLOSE)', 'Team W/L (1/0)', 'Team Over/Under Proj Team Total (1/0)', 'Team ML + Opp Team Over Win/Loss (1/0)', 'SPREAD_ABS', 'points_bucket', 'spread_bucket']

,BIGDATABALL DATASET,GAME-ID,DATE,TEAM,F,OPENING TOTAL,CLOSING SPREAD,CLOSING TOTAL,CLOSING MONEYLINE,PROJ TEAM TOTAL (CLOSE),Team W/L (1/0),Team Over/Under Proj Team Total (1/0),Team ML + Opp Team Over Win/Loss (1/0),SPREAD_ABS,points_bucket,spread_bucket
131,NCAAB 2024-2025 Regular Season,401721074,11/4/2024,Coastal Carolina Chanticleers,60,144.5,-4.5,140.5,-215.0,72.5,1,0,0.0,4.5,low,1–5
191,NCAAB 2024-2025 Regular Season,401700387,11/4/2024,La Salle Explorers,65,136.5,-4.5,136.5,-220.0,70.5,1,0,0.0,4.5,low,1–5
255,NCAAB 2024-2025 Regular Season,401721762,11/4/2024,Army Black Knights,67,143.5,-1.5,143.5,-130.0,72.5,1,0,0.0,1.5,low,1–5
655,NCAAB 2024-2025 Regular Season,401711703,11/8/2024,Queens University Royals,67,157.5,-4.5,159.0,-192.0,81.75,1,0,0.0,4.5,low,1–5
724,NCAAB 2024-2025 Regular Season,401720978,11/8/2024,UC Irvine Anteaters,66,150.5,-1.5,151.0,-125.0,76.25,1,0,0.0,1.5,low,1–5
881,NCAAB 2024-2025 Regular Season,401727833,11/10/2024,Drake Bulldogs,66,142.5,-4.0,139.5,-192.0,71.75,1,0,0.0,4.0,low,1–5
1046,NCAAB 2024-2025 Regular Season,401722095,11/12/2024,Fairfield Stags,62,151.5,-1.5,152.5,-125.0,77,1,0,0.0,1.5,low,1–5
1209,NCAAB 2024-2025 Regular Season,401718458,11/13/2024,Charlotte 49ers,65,142.5,-1.5,141.5,-125.0,71.5,1,0,0.0,1.5,low,1–5
1515,NCAAB 2024-2025 Regular Season,401715390,11/16/2024,Minnesota Golden Gophers,59,138.5,-4.5,138.5,-205.0,71.5,1,0,0.0,4.5,low,1–5
1563,NCAAB 2024-2025 Regular Season,401726049,11/16/2024,Towson Tigers,67,138.5,-2.0,136.5,-130.0,69.25,1,0,0.0,2.0,low,1–5
1721,NCAAB 2024-2025 Regular Season,401720885,11/18/2024,Cal State Fullerton Titans,62,130.5,-2.5,134.0,-142.0,68.25,1,0,0.0,2.5,low,1–5
1859,NCAAB 2024-2025 Regular Season,401721947,11/20/2024,Morehead State Eagles,63,138.5,-1.0,138.0,-112.0,69.5,1,0,0.0,1.0,low,1–5
2048,NCAAB 2024-2025 Regular Season,401726043,11/22/2024,Northeastern Huskies,60,148.5,-4.5,149.5,-198.0,77,1,0,0.0,4.5,low,1–5
2117,NCAAB 2024-2025 Regular Season,401729790,11/22/2024,Nevada Wolf Pack,64,140.5,-1.5,138.5,-120.0,70,1,0,0.0,1.5,low,1–5
2267,NCAAB 2024-2025 Regular Season,401727836,11/23/2024,Stephen F. Austin Lumberjacks,64,128.5,-3.5,129.0,-162.0,66.25,1,0,0.0,3.5,low,1–5
2306,NCAAB 2024-2025 Regular Season,401720668,11/24/2024,Omaha Mavericks,65,153.5,-1.5,150.5,-125.0,76,1,0,0.0,1.5,low,1–5
2341,NCAAB 2024-2025 Regular Season,401726392,11/24/2024,Florida Gulf Coast Eagles,60,135.5,-4.5,135.0,-192.0,69.75,1,0,0.0,4.5,low,1–5
2355,NCAAB 2024-2025 Regular Season,401722594,11/24/2024,Evansville Purple Aces,66,144.5,-4.0,145.5,-180.0,74.75,1,0,0.0,4.0,low,1–5
2457,NCAAB 2024-2025 Regular Season,401722012,11/25/2024,Stonehill Skyhawks,67,137.5,-2.0,137.5,-135.0,69.75,1,0,0.0,2.0,low,1–5
2632,NCAAB 2024-2025 Regular Season,401724518,11/26/2024,Furman Paladins,61,141.5,-1.0,141.5,-108.0,71.25,1,0,0.0,1.0,low,1–5
2714,NCAAB 2024-2025 Regular Season,401718420,11/27/2024,Massachusetts Minutemen,62,146.5,-3.0,148.5,-155.0,75.75,1,0,0.0,3.0,low,1–5
2816,NCAAB 2024-2025 Regular Season,401721032,11/28/2024,Kent State Golden Flashes,65,130.5,-2.0,131.5,-135.0,66.75,1,0,0.0,2.0,low,1–5
2843,NCAAB 2024-2025 Regular Season,401729797,11/29/2024,Wake Forest Demon Deacons,57,131.5,-3.5,127.5,-162.0,65.5,1,0,0.0,3.5,low,1–5
2856,NCAAB 2024-2025 Regular Season,401721993,11/29/2024,Niagara Purple Eagles,65,138.5,-2.0,135.0,-125.0,68.5,1,0,0.0,2.0,low,1–5
2880,NCAAB 2024-2025 Regular Season,401716881,11/29/2024,George Mason Patriots,66,141.5,-2.0,140.0,-122.0,71,1,0,0.0,2.0,low,1–5
3005,NCAAB 2024-2025 Regular Season,401727304,11/30/2024,Lafayette Leopards,59,135.5,-4.0,135.0,-192.0,69.5,1,0,0.0,4.0,low,1–5
3047,NCAAB 2024-2025 Regular Season,401722333,11/30/2024,Pacific Tigers,64,138.5,-4.5,138.5,-198.0,71.5,1,0,0.0,4.5,low,1–5
3073,NCAAB 2024-2025 Regular Season,401724549,12/1/2024,Niagara Purple Eagles,60,138.5,-4.0,136.0,-170.0,70,1,0,0.0,4.0,low,1–5
3408,NCAAB 2024-2025 Regular Season,401715349,12/4/2024,Texas Longhorns,63,144.5,-3.5,149.5,-188.0,76.5,1,0,0.0,3.5,low,1–5
3435,NCAAB 2024-2025 Regular Season,401714398,12/5/2024,Oakland Golden Grizzlies,66,136.5,-1.0,139.0,-118.0,70,1,0,0.0,1.0,low,1–5
3441,NCAAB 2024-2025 Regular Season,401715939,12/5/2024,Nicholls Colonels,67,137.5,-3.0,139.5,-148.0,71.25,1,0,0.0,3.0,low,1–5
3534,NCAAB 2024-2025 Regular Season,401724768,12/7/2024,Clemson Tigers,65,146.5,-4.5,148.0,-205.0,76.25,1,0,0.0,4.5,low,1–5
3561,NCAAB 2024-2025 Regular Season,401729757,12/7/2024,Drexel Dragons,60,136.5,-3.5,137.5,-162.0,70.5,1,0,0.0,3.5,low,1–5
3605,NCAAB 2024-2025 Regular Season,401714403,12/7/2024,Youngstown State Penguins,66,130.5,-2.0,132.0,-135.0,67,1,0,0.0,2.0,low,1–5
3656,NCAAB 2024-2025 Regular Season,401726455,12/7/2024,Northwestern State Demons,64,137.5,-4.0,134.5,-185.0,69.25,1,0,0.0,4.0,low,1–5
3659,NCAAB 2024-2025 Regular Season,401720753,12/7/2024,Texas A&M-Corpus Christi Islanders,67,137.5,-1.5,140.5,-126.0,71,1,0,0.0,1.5,low,1–5
3756,NCAAB 2024-2025 Regular Season,401722026,12/8/2024,Wagner Seahawks,63,125.5,-4.5,127.0,-198.0,65.75,1,0,0.0,4.5,low,1–5
3766,NCAAB 2024-2025 Regular Season,401706180,12/8/2024,Siena Saints,66,134.5,-4.5,134.0,-198.0,69.25,1,0,0.0,4.5,low,1–5
3975,NCAAB 2024-2025 Regular Season,401721825,12/13/2024,Merrimack Warriors,64,125.5,-4.0,126.5,-185.0,65.25,1,0,0.0,4.0,low,1–5
3992,NCAAB 2024-2025 Regular Season,401707854,12/14/2024,Tennessee Volunteers,66,146.5,-1.5,148.5,-130.0,75,1,0,0.0,1.5,low,1–5
4092,NCAAB 2024-2025 Regular Season,401722027,12/14/2024,Wagner Seahawks,50,NaN,-2.5,120.5,-142.0,61.5,1,0,0.0,2.5,low,1–5
4116,NCAAB 2024-2025 Regular Season,401721952,12/14/2024,Southern Illinois Salukis,65,133.5,-1.0,134.5,-115.0,67.75,1,0,0.0,1.0,low,1–5
4119,NCAAB 2024-2025 Regular Season,401720981,12/14/2024,Oregon State Beavers,67,136.5,-2.0,137.0,-142.0,69.5,1,0,0.0,2.0,low,1–5
4410,NCAAB 2024-2025 Regular Season,401700459,12/18/2024,Memphis Tigers,64,130.5,-3.5,130.5,-170.0,67,1,0,0.0,3.5,low,1–5
4451,NCAAB 2024-2025 Regular Season,401721781,12/18/2024,Temple Owls,62,147.5,-1.5,148.5,-125.0,75,1,0,0.0,1.5,low,1–5
4452,NCAAB 2024-2025 Regular Season,401721089,12/18/2024,Central Connecticut Blue Devils,64,138.5,-2.5,138.5,-125.0,70.5,1,0,0.0,2.5,low,1–5
4489,NCAAB 2024-2025 Regular Season,401722590,12/18/2024,Bradley Braves,66,144.5,-2.0,141.0,-135.0,71.5,1,0,0.0,2.0,low,1–5
4513,NCAAB 2024-2025 Regular Season,401722420,12/18/2024,Loyola Marymount Lions,60,141.5,-2.0,142.0,-130.0,72,1,0,0.0,2.0,low,1–5
4551,NCAAB 2024-2025 Regular Season,401711690,12/19/2024,Middle Tennessee Blue Raiders,67,147.5,-1.5,148.5,-125.0,75,1,0,0.0,1.5,low,1–5
4559,NCAAB 2024-2025 Regular Season,401700280,12/19/2024,Little Rock Trojans,60,138.5,-3.0,136.5,-162.0,69.75,1,0,0.0,3.0,low,1–5
4580,NCAAB 2024-2025 Regular Season,401715634,12/20/2024,Cincinnati Bearcats,66,138.5,-1.5,137.5,-135.0,69.5,1,0,0.0,1.5,low,1–5
4936,NCAAB 2024-2025 Regular Season,401719079,12/22/2024,Georgetown Hoyas,61,NaN,-2.0,129.0,-125.0,65.5,1,0,0.0,2.0,low,1–5
5341,NCAAB 2024-2025 Regular Season,401719082,12/31/2024,Creighton Bluejays,57,153.5,-1.0,152.0,-112.0,76.5,1,0,0.0,1.0,low,1–5
5423,NCAAB 2024-2025 Regular Season,401721841,1/2/2025,Lehigh Mountain Hawks,66,138.5,-3.0,140.5,-155.0,71.75,1,0,0.0,3.0,low,1–5
5577,NCAAB 2024-2025 Regular Season,401721329,1/4/2025,Nebraska Cornhuskers,66,133.5,-2.5,133.5,-154.0,68,1,0,0.0,2.5,low,1–5
5625,NCAAB 2024-2025 Regular Season,401727869,1/4/2025,Gardner-Webb Runnin' Bulldogs,63,146.5,-3.5,146.5,-188.0,75,1,0,0.0,3.5,low,1–5
5642,NCAAB 2024-2025 Regular Season,401722458,1/4/2025,Indiana State Sycamores,66,150.5,-2.5,149.5,-166.0,76,1,0,0.0,2.5,low,1–5
5687,NCAAB 2024-2025 Regular Season,401725641,1/4/2025,TCU Horned Frogs,63,142.5,-3.5,140.5,-180.0,72,1,0,0.0,3.5,low,1–5
5735,NCAAB 2024-2025 Regular Season,401700298,1/4/2025,UT Martin Skyhawks,66,142.5,-2.5,142.0,-142.0,72.25,1,0,0.0,2.5,low,1–5
5770,NCAAB 2024-2025 Regular Season,401722142,1/4/2025,Southern Jaguars,67,141.5,-1.0,146.5,-118.0,73.75,1,0,0.0,1.0,low,1–5
5786,NCAAB 2024-2025 Regular Season,401722039,1/4/2025,Bethune-Cookman Wildcats,62,139.5,-4.0,145.0,-185.0,74.5,1,0,0.0,4.0,low,1–5
5806,NCAAB 2024-2025 Regular Season,401706305,1/4/2025,Ohio Bobcats,57,147.5,-4.0,149.0,-185.0,76.5,1,0,0.0,4.0,low,1–5
5819,NCAAB 2024-2025 Regular Season,401706571,1/4/2025,California Baptist Lancers,61,142.5,-3.5,141.0,-175.0,72.25,1,0,0.0,3.5,low,1–5
5862,NCAAB 2024-2025 Regular Season,401721942,1/5/2025,Stonehill Skyhawks,64,141.5,-1.0,140.5,-118.0,70.75,1,0,0.0,1.0,low,1–5
5869,NCAAB 2024-2025 Regular Season,401721845,1/5/2025,Bucknell Bison,66,135.5,-2.5,134.5,-148.0,68.5,1,0,0.0,2.5,low,1–5
5949,NCAAB 2024-2025 Regular Season,401724759,1/7/2025,Syracuse Orange,62,155.5,-1.0,153.5,-112.0,77.25,1,0,0.0,1.0,low,1–5
5976,NCAAB 2024-2025 Regular Season,401700299,1/7/2025,SIU Edwardsville Cougars,60,132.5,-2.0,135.0,-135.0,68.5,1,0,0.0,2.0,low,1–5
6035,NCAAB 2024-2025 Regular Season,401724761,1/8/2025,NC State Wolfpack,66,138.5,-2.5,138.5,-148.0,70.5,1,0,0.0,2.5,low,1–5
6053,NCAAB 2024-2025 Regular Season,401721851,1/8/2025,Boston University Terriers,60,127.5,-3.0,125.5,-162.0,64.25,1,0,0.0,3.0,low,1–5
6055,NCAAB 2024-2025 Regular Season,401721850,1/8/2025,Bucknell Bison,65,129.5,-3.5,131.0,-175.0,67.25,1,0,0.0,3.5,low,1–5
6121,NCAAB 2024-2025 Regular Season,401714460,1/9/2025,Wright State Raiders,66,137.5,-3.5,138.5,-162.0,71,1,0,0.0,3.5,low,1–5
6122,NCAAB 2024-2025 Regular Season,401714201,1/9/2025,Charleston Cougars,67,138.5,-1.5,140.0,-122.0,70.75,1,0,0.0,1.5,low,1–5
6124,NCAAB 2024-2025 Regular Season,401714200,1/9/2025,UNC Wilmington Seahawks,64,NaN,-4.5,144.0,-205.0,74.25,1,0,0.0,4.5,low,1–5
6189,NCAAB 2024-2025 Regular Season,401718477,1/9/2025,Portland State Vikings,64,148.5,-3.5,151.0,-170.0,77.25,1,0,0.0,3.5,low,1–5
6204,NCAAB 2024-2025 Regular Season,401706202,1/10/2025,Merrimack Warriors,66,142.5,-2.5,139.5,-155.0,71,1,0,0.0,2.5,low,1–5
6246,NCAAB 2024-2025 Regular Season,401725656,1/11/2025,Kansas Jayhawks,54,136.5,-1.0,137.0,-115.0,69,1,0,0.0,1.0,low,1–5
6273,NCAAB 2024-2025 Regular Season,401722351,1/11/2025,New Mexico Lobos,62,146.5,-3.5,148.0,-166.0,75.75,1,0,0.0,3.5,low,1–5
6285,NCAAB 2024-2025 Regular Season,401714207,1/11/2025,Hofstra Pride,66,130.5,-2.0,133.5,-142.0,67.75,1,0,0.0,2.0,low,1–5
6338,NCAAB 2024-2025 Regular Season,401722471,1/11/2025,Bradley Braves,61,143.5,-3.0,145.0,-162.0,74,1,0,0.0,3.0,low,1–5
6366,NCAAB 2024-2025 Regular Season,401724751,1/11/2025,North Carolina Tar Heels,63,153.5,-4.5,151.5,-205.0,78,1,0,0.0,4.5,low,1–5
6379,NCAAB 2024-2025 Regular Season,401721237,1/11/2025,Alcorn State Braves,62,148.5,-3.5,148.5,-170.0,76,1,0,0.0,3.5,low,1–5
6384,NCAAB 2024-2025 Regular Season,401718478,1/11/2025,Eastern Washington Eagles,65,137.5,-3.5,138.0,-175.0,70.75,1,0,0.0,3.5,low,1–5
6428,NCAAB 2024-2025 Regular Season,401711601,1/11/2025,Queens University Royals,67,143.5,-1.0,146.0,-120.0,73.5,1,0,0.0,1.0,low,1–5
6440,NCAAB 2024-2025 Regular Season,401724364,1/11/2025,Rhode Island Rams,67,144.5,-2.0,141.5,-135.0,71.75,1,0,0.0,2.0,low,1–5
6499,NCAAB 2024-2025 Regular Season,401706581,1/11/2025,Utah Tech Trailblazers,58,133.5,-1.5,136.0,-130.0,68.75,1,0,0.0,1.5,low,1–5
6534,NCAAB 2024-2025 Regular Season,401706209,1/12/2025,Quinnipiac Bobcats,63,142.5,-1.5,145.5,-125.0,73.5,1,0,0.0,1.5,low,1–5
6689,NCAAB 2024-2025 Regular Season,401721861,1/15/2025,Boston University Terriers,63,131.5,-4.0,132.5,-180.0,68.25,1,0,0.0,4.0,low,1–5
6693,NCAAB 2024-2025 Regular Season,401706433,1/15/2025,VMI Keydets,66,146.5,-1.5,147.5,-125.0,74.5,1,0,0.0,1.5,low,1–5
6798,NCAAB 2024-2025 Regular Season,401714546,1/16/2025,App State Mountaineers,62,133.5,-3.0,135.5,-162.0,69.25,1,0,0.0,3.0,low,1–5
6800,NCAAB 2024-2025 Regular Season,401714215,1/16/2025,Charleston Cougars,67,149.5,-4.5,152.5,-205.0,78.5,1,0,0.0,4.5,low,1–5
6804,NCAAB 2024-2025 Regular Season,401714213,1/16/2025,William & Mary Tribe,67,149.5,-4.5,151.5,-180.0,78,1,0,0.0,4.5,low,1–5
6834,NCAAB 2024-2025 Regular Season,401700192,1/16/2025,New Mexico State Aggies,59,142.5,-3.0,142.0,-162.0,72.5,1,0,0.0,3.0,low,1–5
6870,NCAAB 2024-2025 Regular Season,401720547,1/16/2025,Montana Grizzlies,63,145.5,-1.0,145.5,-108.0,73.25,1,0,0.0,1.0,low,1–5
7043,NCAAB 2024-2025 Regular Season,401720818,1/18/2025,NJIT Highlanders,64,NaN,-2.5,130.5,-175.0,66.5,1,0,0.0,2.5,low,1–5
7044,NCAAB 2024-2025 Regular Season,401714549,1/18/2025,Louisiana Ragin' Cajuns,65,140.5,-1.0,140.5,-120.0,70.75,1,0,0.0,1.0,low,1–5
7091,NCAAB 2024-2025 Regular Season,401714550,1/18/2025,South Alabama Jaguars,64,131.5,-3.5,131.0,-170.0,67.25,1,0,0.0,3.5,low,1–5
7172,NCAAB 2024-2025 Regular Season,401706586,1/18/2025,California Baptist Lancers,60,137.5,-2.0,140.0,-130.0,71,1,0,0.0,2.0,low,1–5
7257,NCAAB 2024-2025 Regular Season,401714218,1/20/2025,Drexel Dragons,60,121.5,-3.0,124.0,-155.0,63.5,1,0,0.0,3.0,low,1–5
7282,NCAAB 2024-2025 Regular Season,401721120,1/20/2025,Fairleigh Dickinson Knights,58,NaN,-3.0,145.0,-155.0,74,1,0,0.0,3.0,low,1–5
7309,NCAAB 2024-2025 Regular Season,401708345,1/21/2025,Texas Longhorns,61,148.5,-3.0,147.5,-148.0,75.25,1,0,0.0,3.0,low,1–5
7395,NCAAB 2024-2025 Regular Season,401721873,1/22/2025,Navy Midshipmen,62,131.5,-2.0,131.0,-125.0,66.5,1,0,0.0,2.0,low,1–5
7462,NCAAB 2024-2025 Regular Season,401706228,1/23/2025,Marist Red Foxes,67,126.5,-4.0,125.5,-192.0,64.75,1,1,1.0,4.0,low,1–5
7494,NCAAB 2024-2025 Regular Season,401706226,1/23/2025,Merrimack Warriors,48,NaN,-1.0,120.5,-115.0,60.75,1,0,0.0,1.0,low,1–5
7509,NCAAB 2024-2025 Regular Season,401706593,1/23/2025,Abilene Christian Wildcats,67,127.5,-3.5,129.0,-185.0,66.25,1,1,0.0,3.5,low,1–5
7511,NCAAB 2024-2025 Regular Season,401706592,1/23/2025,UT Arlington Mavericks,65,145.5,-1.0,145.5,-110.0,73.25,1,0,0.0,1.0,low,1–5
7514,NCAAB 2024-2025 Regular Season,401706525,1/23/2025,South Dakota State Jackrabbits,65,142.5,-4.0,142.5,-198.0,73.25,1,0,0.0,4.0,low,1–5
7526,NCAAB 2024-2025 Regular Season,401700324,1/23/2025,Little Rock Trojans,62,130.5,-4.5,131.5,-220.0,68,1,0,0.0,4.5,low,1–5
7624,NCAAB 2024-2025 Regular Season,401724823,1/25/2025,SMU Mustangs,63,145.5,-3.0,147.0,-162.0,75,1,0,0.0,3.0,low,1–5
7685,NCAAB 2024-2025 Regular Season,401714231,1/25/2025,Drexel Dragons,67,146.5,-4.0,145.0,-205.0,74.5,1,0,0.0,4.0,low,1–5
7771,NCAAB 2024-2025 Regular Season,401720759,1/25/2025,Texas A&M-Corpus Christi Islanders,61,NaN,-4.5,151.0,-215.0,77.75,1,0,NaN,4.5,low,1–5
7783,NCAAB 2024-2025 Regular Season,401700329,1/25/2025,SIU Edwardsville Cougars,65,131.5,-2.5,129.5,-160.0,66,1,0,0.0,2.5,low,1–5
7784,NCAAB 2024-2025 Regular Season,401700327,1/25/2025,Southern Indiana Screaming Eagles,64,139.5,-1.0,139.0,-115.0,70,1,0,0.0,1.0,low,1–5
7796,NCAAB 2024-2025 Regular Season,401718482,1/25/2025,Northern Colorado Bears,67,152.5,-4.5,149.5,-230.0,77,1,0,0.0,4.5,low,1–5
7813,NCAAB 2024-2025 Regular Season,401714564,1/25/2025,Troy Trojans,65,130.5,-4.0,132.0,-192.0,68,1,0,0.0,4.0,low,1–5
7849,NCAAB 2024-2025 Regular Season,401722376,1/25/2025,San José State Spartans,67,134.5,-3.5,133.0,-162.0,68.25,1,0,0.0,3.5,low,1–5
7852,NCAAB 2024-2025 Regular Season,401714565,1/25/2025,Southern Miss Golden Eagles,67,149.5,-2.0,148.0,-130.0,75,1,0,0.0,2.0,low,1–5
8092,NCAAB 2024-2025 Regular Season,401725560,1/29/2025,North Texas Mean Green,58,132.5,-4.0,134.0,-198.0,69,1,0,0.0,4.0,low,1–5
8118,NCAAB 2024-2025 Regular Season,401706713,1/29/2025,Saint Mary's Gaels,67,139.5,-4.0,141.5,-192.0,72.75,1,0,0.0,4.0,low,1–5
8150,NCAAB 2024-2025 Regular Season,401721099,1/30/2025,Central Connecticut Blue Devils,63,123.5,-4.0,126.0,-185.0,65,1,0,0.0,4.0,low,1–5
8266,NCAAB 2024-2025 Regular Season,401706235,1/31/2025,Niagara Purple Eagles,64,137.5,-4.0,135.5,-185.0,69.75,1,0,0.0,4.0,low,1–5
8279,NCAAB 2024-2025 Regular Season,401708366,2/1/2025,Tennessee Volunteers,64,142.5,-1.5,145.5,-130.0,73.5,1,0,0.0,1.5,low,1–5
8329,NCAAB 2024-2025 Regular Season,401706352,2/1/2025,Western Michigan Broncos,61,153.5,-2.5,151.0,-142.0,76.75,1,0,0.0,2.5,low,1–5
8363,NCAAB 2024-2025 Regular Season,401720833,2/1/2025,Vermont Catamounts,55,126.5,-2.0,126.0,-135.0,64,1,0,0.0,2.0,low,1–5
8418,NCAAB 2024-2025 Regular Season,401724402,2/1/2025,George Mason Patriots,64,133.5,-1.0,133.0,-120.0,67,1,0,0.0,1.0,low,1–5
8577,NCAAB 2024-2025 Regular Season,401714435,2/2/2025,Wright State Raiders,66,151.5,-3.0,153.5,-162.0,78.25,1,0,0.0,3.0,low,1–5
8596,NCAAB 2024-2025 Regular Season,401706242,2/2/2025,Merrimack Warriors,66,NaN,-4.5,128.5,-205.0,66.5,1,0,1.0,4.5,low,1–5
8641,NCAAB 2024-2025 Regular Season,401725571,2/3/2025,UAB Blazers,64,137.5,-3.0,136.0,-155.0,69.5,1,0,0.0,3.0,low,1–5
8651,NCAAB 2024-2025 Regular Season,401721404,2/4/2025,UCLA Bruins,63,140.5,-2.0,141.0,-130.0,71.5,1,0,0.0,2.0,low,1–5
8666,NCAAB 2024-2025 Regular Season,401725572,2/4/2025,Wichita State Shockers,66,143.5,-2.0,143.5,-130.0,72.75,1,0,0.0,2.0,low,1–5
8676,NCAAB 2024-2025 Regular Season,401722511,2/4/2025,Drake Bulldogs,55,122.5,-4.5,123.5,-205.0,64,1,0,0.0,4.5,low,1–5
8742,NCAAB 2024-2025 Regular Season,401724412,2/5/2025,George Mason Patriots,53,132.5,-2.5,131.5,-154.0,67,1,0,0.0,2.5,low,1–5
8750,NCAAB 2024-2025 Regular Season,401722515,2/5/2025,Northern Iowa Panthers,66,131.5,-4.5,132.5,-200.0,68.5,1,0,0.0,4.5,low,1–5
8765,NCAAB 2024-2025 Regular Season,401714586,2/5/2025,James Madison Dukes,64,135.5,-1.5,134.5,-120.0,68,1,0,0.0,1.5,low,1–5
8787,NCAAB 2024-2025 Regular Season,401725717,2/5/2025,TCU Horned Frogs,65,128.5,-1.5,128.5,-122.0,65,1,0,0.0,1.5,low,1–5
8788,NCAAB 2024-2025 Regular Season,401725574,2/5/2025,Tulane Green Wave,61,148.5,-2.5,147.5,-135.0,75,1,0,0.0,2.5,low,1–5
8836,NCAAB 2024-2025 Regular Season,401722031,2/6/2025,Long Island University Sharks,60,118.5,-1.0,119.0,-115.0,60,1,0,0.0,1.0,low,1–5
9003,NCAAB 2024-2025 Regular Season,401721894,2/8/2025,Lafayette Leopards,61,137.5,-2.0,138.0,-125.0,70,1,0,0.0,2.0,low,1–5
9049,NCAAB 2024-2025 Regular Season,401722020,2/8/2025,Long Island University Sharks,62,129.5,-2.5,130.0,-142.0,66.25,1,0,0.0,2.5,low,1–5
9137,NCAAB 2024-2025 Regular Season,401706465,2/8/2025,East Tennessee State Buccaneers,66,147.5,-1.0,149.5,-112.0,75.25,1,0,0.0,1.0,low,1–5
9139,NCAAB 2024-2025 Regular Season,401700349,2/8/2025,Tennessee Tech Golden Eagles,59,138.5,-4.5,139.5,-205.0,72,1,0,0.0,4.5,low,1–5
9258,NCAAB 2024-2025 Regular Season,401706729,2/8/2025,Saint Mary's Gaels,63,129.5,-4.5,129.0,-205.0,66.75,1,0,0.0,4.5,low,1–5
9283,NCAAB 2024-2025 Regular Season,401721899,2/10/2025,American University Eagles,60,131.5,-3.0,133.5,-162.0,68.25,1,0,0.0,3.0,low,1–5
9367,NCAAB 2024-2025 Regular Season,401722523,2/11/2025,Murray State Racers,63,146.5,-3.5,145.5,-175.0,74.5,1,0,0.0,3.5,low,1–5
9441,NCAAB 2024-2025 Regular Season,401721902,2/12/2025,Navy Midshipmen,63,140.5,-3.5,138.5,-166.0,71,1,0,0.0,3.5,low,1–5
9525,NCAAB 2024-2025 Regular Season,401714264,2/13/2025,William & Mary Tribe,61,145.5,-2.5,145.5,-155.0,74,1,0,0.0,2.5,low,1–5
9537,NCAAB 2024-2025 Regular Season,401700228,2/13/2025,Sam Houston Bearkats,66,142.5,-2.5,143.5,-155.0,73,1,0,0.0,2.5,low,1–5
9564,NCAAB 2024-2025 Regular Season,401700355,2/13/2025,Tennessee State Tigers,66,142.5,-1.5,142.5,-125.0,72,1,0,0.0,1.5,low,1–5
9574,NCAAB 2024-2025 Regular Season,401700231,2/13/2025,Liberty Flames,64,132.5,-3.5,133.5,-162.0,68.5,1,0,0.0,3.5,low,1–5
9613,NCAAB 2024-2025 Regular Season,401706262,2/14/2025,Saint Peter's Peacocks,65,NaN,-4.5,132.5,-200.0,68.5,1,0,0.0,4.5,low,1–5
9636,NCAAB 2024-2025 Regular Season,401725738,2/15/2025,Houston Cougars,62,137.5,-2.5,137.5,-142.0,70,1,0,0.0,2.5,low,1–5
9669,NCAAB 2024-2025 Regular Season,401724428,2/15/2025,George Mason Patriots,58,132.5,-4.5,134.5,-205.0,69.5,1,0,0.0,4.5,low,1–5
9685,NCAAB 2024-2025 Regular Season,401721906,2/15/2025,Navy Midshipmen,61,143.5,-3.5,143.5,-175.0,73.5,1,0,0.0,3.5,low,1–5
9699,NCAAB 2024-2025 Regular Season,401721146,2/15/2025,Long Island University Sharks,62,NaN,-3.5,136.5,-155.0,70,1,0,0.0,3.5,low,1–5

Rows matched: 207

In [19]:
# Favorite rows matching your condition
df_fav = df[df["CLOSING SPREAD"] < 0].copy()

mask = (
    (df_fav["spread_bucket"] == "1–5") &
    (df_fav["points_bucket"] == "low") &
    (df_fav["Team W/L (1/0)"] == 1)
)

game_ids = df_fav.loc[mask, "GAME-ID"].unique()

# Underdog rows from those same games
df_udog_same_games = df[(df["CLOSING SPREAD"] > 0) & (df["GAME-ID"].isin(game_ids))].copy()

display(df_udog_same_games)
print("Underdog rows (same games):", len(df_udog_same_games))

,BIGDATABALL DATASET,GAME-ID,DATE,TEAM,F,OPENING TOTAL,CLOSING SPREAD,CLOSING TOTAL,CLOSING MONEYLINE,PROJ TEAM TOTAL (CLOSE),Team W/L (1/0),Team Over/Under Proj Team Total (1/0),Team ML + Opp Team Over Win/Loss (1/0),SPREAD_ABS,points_bucket,spread_bucket
130,NCAAB 2024-2025 Regular Season,401721074,11/4/2024,Western Michigan Broncos,56,144.5,4.5,140.5,165.0,68,0,0,0.0,4.5,low,1–5
190,NCAAB 2024-2025 Regular Season,401700387,11/4/2024,American University Eagles,52,136.5,4.5,136.5,170.0,66,0,0,0.0,4.5,low,1–5
254,NCAAB 2024-2025 Regular Season,401721762,11/4/2024,UAlbany Great Danes,59,143.5,1.5,143.5,NaN,71,0,0,0.0,1.5,low,1–5
654,NCAAB 2024-2025 Regular Season,401711703,11/8/2024,Western Carolina Catamounts,54,157.5,4.5,159.0,152.0,77.25,0,0,0.0,4.5,low,1–5
725,NCAAB 2024-2025 Regular Season,401720978,11/8/2024,Loyola Marymount Lions,51,150.5,1.5,151.0,105.0,74.75,0,0,0.0,1.5,low,1–5
880,NCAAB 2024-2025 Regular Season,401727833,11/10/2024,Stephen F. Austin Lumberjacks,51,142.5,4.0,139.5,160.0,67.75,0,0,0.0,4.0,low,1–5
1047,NCAAB 2024-2025 Regular Season,401722095,11/12/2024,New Hampshire Wildcats,56,151.5,1.5,152.5,105.0,75.5,0,0,0.0,1.5,low,1–5
1208,NCAAB 2024-2025 Regular Season,401718458,11/13/2024,Richmond Spiders,48,142.5,1.5,141.5,105.0,70,0,0,0.0,1.5,low,1–5
1514,NCAAB 2024-2025 Regular Season,401715390,11/16/2024,Yale Bulldogs,56,138.5,4.5,138.5,170.0,67,0,0,0.0,4.5,low,1–5
1562,NCAAB 2024-2025 Regular Season,401726049,11/16/2024,James Madison Dukes,63,138.5,2.0,136.5,110.0,67.25,0,0,0.0,2.0,low,1–5
1720,NCAAB 2024-2025 Regular Season,401720885,11/18/2024,Idaho State Bengals,61,130.5,2.5,134.0,120.0,65.75,0,0,0.0,2.5,low,1–5
1858,NCAAB 2024-2025 Regular Season,401721947,11/20/2024,Austin Peay Governors,58,138.5,1.0,138.0,-108.0,68.5,0,0,0.0,1.0,low,1–5
2049,NCAAB 2024-2025 Regular Season,401726043,11/22/2024,Florida International Panthers,58,148.5,4.5,149.5,164.0,72.5,0,0,0.0,4.5,low,1–5
2116,NCAAB 2024-2025 Regular Season,401729790,11/22/2024,VCU Rams,61,140.5,1.5,138.5,NaN,68.5,0,0,0.0,1.5,low,1–5
2266,NCAAB 2024-2025 Regular Season,401727836,11/23/2024,Youngstown State Penguins,57,128.5,3.5,129.0,136.0,62.75,0,0,0.0,3.5,low,1–5
2307,NCAAB 2024-2025 Regular Season,401720668,11/24/2024,Lamar Cardinals,59,153.5,1.5,150.5,105.0,74.5,0,0,0.0,1.5,low,1–5
2340,NCAAB 2024-2025 Regular Season,401726392,11/24/2024,Florida International Panthers,59,135.5,4.5,135.0,160.0,65.25,0,0,0.0,4.5,low,1–5
2354,NCAAB 2024-2025 Regular Season,401722594,11/24/2024,Campbell Fighting Camels,53,144.5,4.0,145.5,150.0,70.75,0,0,0.0,4.0,low,1–5
2456,NCAAB 2024-2025 Regular Season,401722012,11/25/2024,East Texas A&M Lions,65,137.5,2.0,137.5,114.0,67.75,0,0,0.0,2.0,low,1–5
2633,NCAAB 2024-2025 Regular Season,401724518,11/26/2024,Seattle U Redhawks,56,141.5,1.0,141.5,-112.0,70.25,0,0,0.0,1.0,low,1–5
2715,NCAAB 2024-2025 Regular Season,401718420,11/27/2024,Harvard Crimson,54,146.5,3.0,148.5,130.0,72.75,0,0,0.0,3.0,low,1–5
2817,NCAAB 2024-2025 Regular Season,401721032,11/28/2024,Towson Tigers,54,130.5,2.0,131.5,114.0,64.75,0,0,0.0,2.0,low,1–5
2842,NCAAB 2024-2025 Regular Season,401729797,11/29/2024,Minnesota Golden Gophers,51,131.5,3.5,127.5,136.0,62,0,0,0.0,3.5,low,1–5
2857,NCAAB 2024-2025 Regular Season,401721993,11/29/2024,Binghamton Bearcats,62,138.5,2.0,135.0,105.0,66.5,0,0,0.0,2.0,low,1–5
2881,NCAAB 2024-2025 Regular Season,401716881,11/29/2024,James Madison Dukes,61,141.5,2.0,140.0,102.0,69,0,0,0.0,2.0,low,1–5
3004,NCAAB 2024-2025 Regular Season,401727304,11/30/2024,Niagara Purple Eagles,47,135.5,4.0,135.0,160.0,65.5,0,0,0.0,4.0,low,1–5
3046,NCAAB 2024-2025 Regular Season,401722333,11/30/2024,Cal State Fullerton Titans,55,138.5,4.5,138.5,164.0,67,0,0,0.0,4.5,low,1–5
3072,NCAAB 2024-2025 Regular Season,401724549,12/1/2024,Long Island University Sharks,52,138.5,4.0,136.0,142.0,66,0,0,0.0,4.0,low,1–5
3409,NCAAB 2024-2025 Regular Season,401715349,12/4/2024,NC State Wolfpack,59,144.5,3.5,149.5,145.0,73,0,0,0.0,3.5,low,1–5
3434,NCAAB 2024-2025 Regular Season,401714398,12/5/2024,Wright State Raiders,64,136.5,1.0,139.0,-102.0,69,0,0,0.0,1.0,low,1–5
3440,NCAAB 2024-2025 Regular Season,401715939,12/5/2024,SE Louisiana Lions,64,137.5,3.0,139.5,124.0,68.25,0,0,0.0,3.0,low,1–5
3535,NCAAB 2024-2025 Regular Season,401724768,12/7/2024,Miami Hurricanes,55,146.5,4.5,148.0,170.0,71.75,0,0,0.0,4.5,low,1–5
3560,NCAAB 2024-2025 Regular Season,401729757,12/7/2024,Pennsylvania Quakers,47,136.5,3.5,137.5,136.0,67,0,0,0.0,3.5,low,1–5
3604,NCAAB 2024-2025 Regular Season,401714403,12/7/2024,Oakland Golden Grizzlies,50,130.5,2.0,132.0,114.0,65,0,0,0.0,2.0,low,1–5
3657,NCAAB 2024-2025 Regular Season,401726455,12/7/2024,Houston Christian Huskies,57,137.5,4.0,134.5,154.0,65.25,0,0,0.0,4.0,low,1–5
3658,NCAAB 2024-2025 Regular Season,401720753,12/7/2024,Stephen F. Austin Lumberjacks,48,137.5,1.5,140.5,105.0,69.5,0,0,0.0,1.5,low,1–5
3757,NCAAB 2024-2025 Regular Season,401722026,12/8/2024,Maryland Eastern Shore Hawks,61,125.5,4.5,127.0,164.0,61.25,0,0,0.0,4.5,low,1–5
3767,NCAAB 2024-2025 Regular Season,401706180,12/8/2024,Canisius Golden Griffins,53,134.5,4.5,134.0,164.0,64.75,0,0,0.0,4.5,low,1–5
3974,NCAAB 2024-2025 Regular Season,401721825,12/13/2024,Boston University Terriers,61,125.5,4.0,126.5,154.0,61.25,0,0,0.0,4.0,low,1–5
3993,NCAAB 2024-2025 Regular Season,401707854,12/14/2024,Illinois Fighting Illini,64,146.5,1.5,148.5,110.0,73.5,0,0,0.0,1.5,low,1–5
4093,NCAAB 2024-2025 Regular Season,401722027,12/14/2024,NJIT Highlanders,43,NaN,2.5,120.5,120.0,59,0,0,0.0,2.5,low,1–5
4117,NCAAB 2024-2025 Regular Season,401721952,12/14/2024,Austin Peay Governors,60,133.5,1.0,134.5,-105.0,66.75,0,0,0.0,1.0,low,1–5
4118,NCAAB 2024-2025 Regular Season,401720981,12/14/2024,UC Irvine Anteaters,55,136.5,2.0,137.0,120.0,67.5,0,0,0.0,2.0,low,1–5
4411,NCAAB 2024-2025 Regular Season,401700459,12/18/2024,Virginia Cavaliers,62,130.5,3.5,130.5,142.0,63.5,0,0,0.0,3.5,low,1–5
4450,NCAAB 2024-2025 Regular Season,401721781,12/18/2024,Davidson Wildcats,61,147.5,1.5,148.5,105.0,73.5,0,0,0.0,1.5,low,1–5
4453,NCAAB 2024-2025 Regular Season,401721089,12/18/2024,Fairfield Stags,63,138.5,2.5,138.5,105.0,68,0,0,0.0,2.5,low,1–5
4488,NCAAB 2024-2025 Regular Season,401722590,12/18/2024,San Francisco Dons,64,144.5,2.0,141.0,114.0,69.5,0,0,0.0,2.0,low,1–5
4512,NCAAB 2024-2025 Regular Season,401722420,12/18/2024,UC Santa Barbara Gauchos,58,141.5,2.0,142.0,110.0,70,0,0,0.0,2.0,low,1–5
4550,NCAAB 2024-2025 Regular Season,401711690,12/19/2024,Lipscomb Bisons,65,147.5,1.5,148.5,105.0,73.5,0,0,0.0,1.5,low,1–5
4558,NCAAB 2024-2025 Regular Season,401700280,12/19/2024,SIU Edwardsville Cougars,56,138.5,3.0,136.5,136.0,66.75,0,0,0.0,3.0,low,1–5
4581,NCAAB 2024-2025 Regular Season,401715634,12/20/2024,Dayton Flyers,59,138.5,1.5,137.5,105.0,68,0,0,0.0,1.5,low,1–5
4937,NCAAB 2024-2025 Regular Season,401719079,12/22/2024,Seton Hall Pirates,60,NaN,2.0,129.0,105.0,63.5,0,0,0.0,2.0,low,1–5
5340,NCAAB 2024-2025 Regular Season,401719082,12/31/2024,St. John's Red Storm,56,153.5,1.0,152.0,-108.0,75.5,0,0,0.0,1.0,low,1–5
5422,NCAAB 2024-2025 Regular Season,401721841,1/2/2025,Bucknell Bison,64,138.5,3.0,140.5,130.0,68.75,0,0,0.0,3.0,low,1–5
5576,NCAAB 2024-2025 Regular Season,401721329,1/4/2025,UCLA Bruins,58,133.5,2.5,133.5,120.0,65.5,0,0,0.0,2.5,low,1–5
5624,NCAAB 2024-2025 Regular Season,401727869,1/4/2025,Presbyterian Blue Hose,61,146.5,3.5,146.5,145.0,71.5,0,0,0.0,3.5,low,1–5
5643,NCAAB 2024-2025 Regular Season,401722458,1/4/2025,Evansville Purple Aces,62,150.5,2.5,149.5,130.0,73.5,0,0,0.0,2.5,low,1–5
5686,NCAAB 2024-2025 Regular Season,401725641,1/4/2025,Kansas State Wildcats,62,142.5,3.5,140.5,140.0,68.5,0,0,0.0,3.5,low,1–5
5734,NCAAB 2024-2025 Regular Season,401700298,1/4/2025,Southeast Missouri State Redhawks,63,142.5,2.5,142.0,120.0,69.75,0,0,0.0,2.5,low,1–5
5771,NCAAB 2024-2025 Regular Season,401722142,1/4/2025,Texas Southern Tigers,58,141.5,1.0,146.5,-102.0,72.75,0,0,0.0,1.0,low,1–5
5787,NCAAB 2024-2025 Regular Season,401722039,1/4/2025,Florida A&M Rattlers,55,139.5,4.0,145.0,154.0,70.5,0,0,0.0,4.0,low,1–5
5807,NCAAB 2024-2025 Regular Season,401706305,1/4/2025,Central Michigan Chippewas,55,147.5,4.0,149.0,154.0,72.5,0,0,0.0,4.0,low,1–5
5818,NCAAB 2024-2025 Regular Season,401706571,1/4/2025,Seattle U Redhawks,59,142.5,3.5,141.0,145.0,68.75,0,0,0.0,3.5,low,1–5
5863,NCAAB 2024-2025 Regular Season,401721942,1/5/2025,St. Francis (PA) Red Flash,60,141.5,1.0,140.5,-102.0,69.75,0,0,0.0,1.0,low,1–5
5868,NCAAB 2024-2025 Regular Season,401721845,1/5/2025,Colgate Raiders,60,135.5,2.5,134.5,124.0,66,0,0,0.0,2.5,low,1–5
5948,NCAAB 2024-2025 Regular Season,401724759,1/7/2025,Georgia Tech Yellow Jackets,55,155.5,1.0,153.5,-108.0,76.25,0,0,0.0,1.0,low,1–5
5977,NCAAB 2024-2025 Regular Season,401700299,1/7/2025,Eastern Illinois Panthers,57,132.5,2.0,135.0,114.0,66.5,0,0,0.0,2.0,low,1–5
6034,NCAAB 2024-2025 Regular Season,401724761,1/8/2025,Notre Dame Fighting Irish,65,138.5,2.5,138.5,124.0,68,0,0,0.0,2.5,low,1–5
6052,NCAAB 2024-2025 Regular Season,401721851,1/8/2025,American University Eagles,54,127.5,3.0,125.5,136.0,61.25,0,0,0.0,3.0,low,1–5
6054,NCAAB 2024-2025 Regular Season,401721850,1/8/2025,Lafayette Leopards,62,129.5,3.5,131.0,145.0,63.75,0,0,0.0,3.5,low,1–5
6120,NCAAB 2024-2025 Regular Season,401714460,1/9/2025,Oakland Golden Grizzlies,62,137.5,3.5,138.5,136.0,67.5,0,0,0.0,3.5,low,1–5
6123,NCAAB 2024-2025 Regular Season,401714201,1/9/2025,Hofstra Pride,61,138.5,1.5,140.0,102.0,69.25,0,0,0.0,1.5,low,1–5
6125,NCAAB 2024-2025 Regular Season,401714200,1/9/2025,Monmouth Hawks,55,NaN,4.5,144.0,170.0,69.75,0,0,0.0,4.5,low,1–5
6188,NCAAB 2024-2025 Regular Season,401718477,1/9/2025,Eastern Washington Eagles,59,148.5,3.5,151.0,142.0,73.75,0,0,0.0,3.5,low,1–5
6205,NCAAB 2024-2025 Regular Season,401706202,1/10/2025,Sacred Heart Pioneers,65,142.5,2.5,139.5,130.0,68.5,0,0,0.0,2.5,low,1–5
6247,NCAAB 2024-2025 Regular Season,401725656,1/11/2025,Cincinnati Bearcats,40,136.5,1.0,137.0,-105.0,68,0,0,0.0,1.0,low,1–5
6272,NCAAB 2024-2025 Regular Season,401722351,1/11/2025,San Diego State Aztecs,48,146.5,3.5,148.0,140.0,72.25,0,0,0.0,3.5,low,1–5
6284,NCAAB 2024-2025 Regular Season,401714207,1/11/2025,UNC Wilmington Seahawks,63,130.5,2.0,133.5,120.0,65.75,0,0,0.0,2.0,low,1–5
6339,NCAAB 2024-2025 Regular Season,401722471,1/11/2025,UIC Flames,60,143.5,3.0,145.0,136.0,71,0,0,0.0,3.0,low,1–5
6367,NCAAB 2024-2025 Regular Season,401724751,1/11/2025,NC State Wolfpack,61,153.5,4.5,151.5,170.0,73.5,0,0,0.0,4.5,low,1–5
6378,NCAAB 2024-2025 Regular Season,401721237,1/11/2025,Alabama A&M Bulldogs,52,148.5,3.5,148.5,142.0,72.5,0,0,0.0,3.5,low,1–5
6385,NCAAB 2024-2025 Regular Season,401718478,1/11/2025,Sacramento State Hornets,54,137.5,3.5,138.0,145.0,67.25,0,0,0.0,3.5,low,1–5
6429,NCAAB 2024-2025 Regular Season,401711601,1/11/2025,Austin Peay Governors,60,143.5,1.0,146.0,NaN,72.5,0,0,0.0,1.0,low,1–5
6441,NCAAB 2024-2025 Regular Season,401724364,1/11/2025,Richmond Spiders,64,144.5,2.0,141.5,114.0,69.75,0,0,0.0,2.0,low,1–5
6498,NCAAB 2024-2025 Regular Season,401706581,1/11/2025,Tarleton State Texans,54,133.5,1.5,136.0,110.0,67.25,0,0,0.0,1.5,low,1–5
6535,NCAAB 2024-2025 Regular Season,401706209,1/12/2025,Iona Gaels,62,142.5,1.5,145.5,105.0,72,0,0,0.0,1.5,low,1–5
6688,NCAAB 2024-2025 Regular Season,401721861,1/15/2025,Lehigh Mountain Hawks,58,131.5,4.0,132.5,150.0,64.25,0,0,0.0,4.0,low,1–5
6692,NCAAB 2024-2025 Regular Season,401706433,1/15/2025,Western Carolina Catamounts,50,146.5,1.5,147.5,105.0,73,0,0,0.0,1.5,low,1–5
6799,NCAAB 2024-2025 Regular Season,401714546,1/16/2025,Old Dominion Monarchs,43,133.5,3.0,135.5,136.0,66.25,0,0,0.0,3.0,low,1–5
6801,NCAAB 2024-2025 Regular Season,401714215,1/16/2025,Campbell Fighting Camels,61,149.5,4.5,152.5,170.0,74,0,0,0.0,4.5,low,1–5
6805,NCAAB 2024-2025 Regular Season,401714213,1/16/2025,Hampton Pirates,64,149.5,4.5,151.5,150.0,73.5,0,0,0.0,4.5,low,1–5
6835,NCAAB 2024-2025 Regular Season,401700192,1/16/2025,Florida International Panthers,52,142.5,3.0,142.0,136.0,69.5,0,0,0.0,3.0,low,1–5
6871,NCAAB 2024-2025 Regular Season,401720547,1/16/2025,Weber State Wildcats,59,145.5,1.0,145.5,-112.0,72.25,0,0,0.0,1.0,low,1–5
7042,NCAAB 2024-2025 Regular Season,401720818,1/18/2025,New Hampshire Wildcats,59,NaN,2.5,130.5,135.0,64,0,0,0.0,2.5,low,1–5
7045,NCAAB 2024-2025 Regular Season,401714549,1/18/2025,UL Monroe Warhawks,60,140.5,1.0,140.5,NaN,69.75,0,0,0.0,1.0,low,1–5
7090,NCAAB 2024-2025 Regular Season,401714550,1/18/2025,Troy Trojans,63,131.5,3.5,131.0,142.0,63.75,0,0,0.0,3.5,low,1–5
7173,NCAAB 2024-2025 Regular Season,401706586,1/18/2025,Abilene Christian Wildcats,54,137.5,2.0,140.0,110.0,69,0,0,0.0,2.0,low,1–5
7256,NCAAB 2024-2025 Regular Season,401714218,1/20/2025,Hofstra Pride,55,121.5,3.0,124.0,130.0,60.5,0,0,0.0,3.0,low,1–5
7283,NCAAB 2024-2025 Regular Season,401721120,1/20/2025,Chicago State Cougars,48,NaN,3.0,145.0,130.0,71,0,0,0.0,3.0,low,1–5
7308,NCAAB 2024-2025 Regular Season,401708345,1/21/2025,Missouri Tigers,53,148.5,3.0,147.5,124.0,72.25,0,0,0.0,3.0,low,1–5
7394,NCAAB 2024-2025 Regular Season,401721873,1/22/2025,Boston University Terriers,47,131.5,2.0,131.0,105.0,64.5,0,0,0.0,2.0,low,1–5
7463,NCAAB 2024-2025 Regular Season,401706228,1/23/2025,Niagara Purple Eagles,65,126.5,4.0,125.5,160.0,60.75,0,1,0.0,4.0,low,1–5
7495,NCAAB 2024-2025 Regular Season,401706226,1/23/2025,Saint Peter's Peacocks,37,NaN,1.0,120.5,-105.0,59.75,0,0,0.0,1.0,low,1–5
7508,NCAAB 2024-2025 Regular Season,401706593,1/23/2025,Tarleton State Texans,56,127.5,3.5,129.0,154.0,62.75,0,0,0.0,3.5,low,1–5
7510,NCAAB 2024-2025 Regular Season,401706592,1/23/2025,Seattle U Redhawks,56,145.5,1.0,145.5,-110.0,72.25,0,0,0.0,1.0,low,1–5
7515,NCAAB 2024-2025 Regular Season,401706525,1/23/2025,Kansas City Roos,64,142.5,4.0,142.5,164.0,69.25,0,0,0.0,4.0,low,1–5
7527,NCAAB 2024-2025 Regular Season,401700324,1/23/2025,Western Illinois Leathernecks,51,130.5,4.5,131.5,170.0,63.5,0,0,0.0,4.5,low,1–5
7625,NCAAB 2024-2025 Regular Season,401724823,1/25/2025,NC State Wolfpack,57,145.5,3.0,147.0,136.0,72,0,0,0.0,3.0,low,1–5
7684,NCAAB 2024-2025 Regular Season,401714231,1/25/2025,Delaware Blue Hens,54,146.5,4.0,145.0,170.0,70.5,0,0,0.0,4.0,low,1–5
7782,NCAAB 2024-2025 Regular Season,401700329,1/25/2025,Morehead State Eagles,54,131.5,2.5,129.5,124.0,63.5,0,0,0.0,2.5,low,1–5
7785,NCAAB 2024-2025 Regular Season,401700327,1/25/2025,Eastern Illinois Panthers,60,139.5,1.0,139.0,-105.0,69,0,0,0.0,1.0,low,1–5
7797,NCAAB 2024-2025 Regular Season,401718482,1/25/2025,Eastern Washington Eagles,62,152.5,4.5,149.5,175.0,72.5,0,0,0.0,4.5,low,1–5
7812,NCAAB 2024-2025 Regular Season,401714564,1/25/2025,South Alabama Jaguars,55,130.5,4.0,132.0,160.0,64,0,0,0.0,4.0,low,1–5
7848,NCAAB 2024-2025 Regular Season,401722376,1/25/2025,Wyoming Cowboys,58,134.5,3.5,133.0,136.0,64.75,0,0,0.0,3.5,low,1–5
7853,NCAAB 2024-2025 Regular Season,401714565,1/25/2025,Louisiana Ragin' Cajuns,59,149.5,2.0,148.0,110.0,73,0,0,0.0,2.0,low,1–5
8093,NCAAB 2024-2025 Regular Season,401725560,1/29/2025,Wichita State Shockers,54,132.5,4.0,134.0,164.0,65,0,0,0.0,4.0,low,1–5
8119,NCAAB 2024-2025 Regular Season,401706713,1/29/2025,Santa Clara Broncos,54,139.5,4.0,141.5,160.0,68.75,0,0,0.0,4.0,low,1–5
8151,NCAAB 2024-2025 Regular Season,401721099,1/30/2025,Long Island University Sharks,50,123.5,4.0,126.0,154.0,61,0,0,0.0,4.0,low,1–5
8267,NCAAB 2024-2025 Regular Season,401706235,1/31/2025,Canisius Golden Griffins,63,137.5,4.0,135.5,154.0,65.75,0,0,0.0,4.0,low,1–5
8278,NCAAB 2024-2025 Regular Season,401708366,2/1/2025,Florida Gators,44,142.5,1.5,145.5,110.0,72,0,0,0.0,1.5,low,1–5
8328,NCAAB 2024-2025 Regular Season,401706352,2/1/2025,Eastern Michigan Eagles,54,153.5,2.5,151.0,120.0,74.25,0,0,0.0,2.5,low,1–5
8362,NCAAB 2024-2025 Regular Season,401720833,2/1/2025,Maine Black Bears,49,126.5,2.0,126.0,114.0,62,0,0,0.0,2.0,low,1–5
8419,NCAAB 2024-2025 Regular Season,401724402,2/1/2025,Davidson Wildcats,60,133.5,1.0,133.0,NaN,66,0,0,0.0,1.0,low,1–5
8576,NCAAB 2024-2025 Regular Season,401714435,2/2/2025,Robert Morris Colonials,64,151.5,3.0,153.5,136.0,75.25,0,0,0.0,3.0,low,1–5
8597,NCAAB 2024-2025 Regular Season,401706242,2/2/2025,Rider Broncs,64,NaN,4.5,128.5,170.0,62,0,1,0.0,4.5,low,1–5
8640,NCAAB 2024-2025 Regular Season,401725571,2/3/2025,North Texas Mean Green,61,137.5,3.0,136.0,130.0,66.5,0,0,0.0,3.0,low,1–5
8650,NCAAB 2024-2025 Regular Season,401721404,2/4/2025,Michigan State Spartans,61,140.5,2.0,141.0,110.0,69.5,0,0,0.0,2.0,low,1–5
8667,NCAAB 2024-2025 Regular Season,401725572,2/4/2025,Charlotte 49ers,58,143.5,2.0,143.5,110.0,70.75,0,0,0.0,2.0,low,1–5
8677,NCAAB 2024-2025 Regular Season,401722511,2/4/2025,Murray State Racers,45,122.5,4.5,123.5,170.0,59.5,0,0,0.0,4.5,low,1–5
8743,NCAAB 2024-2025 Regular Season,401724412,2/5/2025,George Washington Revolutionaries,50,132.5,2.5,131.5,120.0,64.5,0,0,0.0,2.5,low,1–5
8751,NCAAB 2024-2025 Regular Season,401722515,2/5/2025,Missouri State Bears,61,131.5,4.5,132.5,154.0,64,0,0,0.0,4.5,low,1–5
8764,NCAAB 2024-2025 Regular Season,401714586,2/5/2025,Troy Trojans,61,135.5,1.5,134.5,-110.0,66.5,0,0,0.0,1.5,low,1–5
8786,NCAAB 2024-2025 Regular Season,401725717,2/5/2025,West Virginia Mountaineers,60,128.5,1.5,128.5,102.0,63.5,0,0,0.0,1.5,low,1–5
8789,NCAAB 2024-2025 Regular Season,401725574,2/5/2025,UTSA Roadrunners,60,148.5,2.5,147.5,114.0,72.5,0,0,0.0,2.5,low,1–5
8837,NCAAB 2024-2025 Regular Season,401722031,2/6/2025,Wagner Seahawks,47,118.5,1.0,119.0,-105.0,59,0,0,0.0,1.0,low,1–5
9002,NCAAB 2024-2025 Regular Season,401721894,2/8/2025,Navy Midshipmen,51,137.5,2.0,138.0,105.0,68,0,0,0.0,2.0,low,1–5
9048,NCAAB 2024-2025 Regular Season,401722020,2/8/2025,Stonehill Skyhawks,59,129.5,2.5,130.0,120.0,63.75,0,0,0.0,2.5,low,1–5
9136,NCAAB 2024-2025 Regular Season,401706465,2/8/2025,Samford Bulldogs,59,147.5,1.0,149.5,-108.0,74.25,0,0,0.0,1.0,low,1–5
9138,NCAAB 2024-2025 Regular Season,401700349,2/8/2025,Eastern Illinois Panthers,54,138.5,4.5,139.5,170.0,67.5,0,0,0.0,4.5,low,1–5
9259,NCAAB 2024-2025 Regular Season,401706729,2/8/2025,Oregon State Beavers,49,129.5,4.5,129.0,170.0,62.25,0,0,0.0,4.5,low,1–5
9282,NCAAB 2024-2025 Regular Season,401721899,2/10/2025,Lafayette Leopards,58,131.5,3.0,133.5,136.0,65.25,0,0,0.0,3.0,low,1–5
9366,NCAAB 2024-2025 Regular Season,401722523,2/11/2025,UIC Flames,53,146.5,3.5,145.5,145.0,71,0,0,0.0,3.5,low,1–5
9440,NCAAB 2024-2025 Regular Season,401721902,2/12/2025,Lehigh Mountain Hawks,60,140.5,3.5,138.5,140.0,67.5,0,0,0.0,3.5,low,1–5
9524,NCAAB 2024-2025 Regular Season,401714264,2/13/2025,Hofstra Pride,60,145.5,2.5,145.5,130.0,71.5,0,0,0.0,2.5,low,1–5
9536,NCAAB 2024-2025 Regular Season,401700228,2/13/2025,Jacksonville State Gamecocks,61,142.5,2.5,143.5,130.0,70.5,0,0,0.0,2.5,low,1–5
9565,NCAAB 2024-2025 Regular Season,401700355,2/13/2025,Eastern Illinois Panthers,49,142.5,1.5,142.5,105.0,70.5,0,0,0.0,1.5,low,1–5
9575,NCAAB 2024-2025 Regular Season,401700231,2/13/2025,New Mexico State Aggies,54,132.5,3.5,133.5,136.0,65,0,0,0.0,3.5,low,1–5
9612,NCAAB 2024-2025 Regular Season,401706262,2/14/2025,Fairfield Stags,52,NaN,4.5,132.5,164.0,64,0,0,0.0,4.5,low,1–5
9637,NCAAB 2024-2025 Regular Season,401725738,2/15/2025,Arizona Wildcats,58,137.5,2.5,137.5,120.0,67.5,0,0,0.0,2.5,low,1–5
9668,NCAAB 2024-2025 Regular Season,401724428,2/15/2025,Saint Joseph's Hawks,57,132.5,4.5,134.5,170.0,65,0,0,0.0,4.5,low,1–5
9684,NCAAB 2024-2025 Regular Season,401721906,2/15/2025,Army Black Knights,54,143.5,3.5,143.5,145.0,70,0,0,0.0,3.5,low,1–5
9698,NCAAB 2024-2025 Regular Season,401721146,2/15/2025,Fairleigh Dickinson Knights,58,NaN,3.5,136.5,130.0,66.5,0,0,0.0,3.5,low,1–5
9731,NCAAB 2024-2025 Regular Season,401706368,2/15/2025,Buffalo Bulls,59,154.5,1.5,153.5,102.0,76,0,0,0.0,1.5,low,1–5
9751,NCAAB 2024-2025 Regular Season,401720681,2/15/2025,East Texas A&M Lions,55,133.5,4.5,134.5,160.0,65,0,0,0.0,4.5,low,1–5
9781,NCAAB 2024-2025 Regular Season,401720934,2/15/2025,Sacramento State Hornets,61,138.5,3.5,138.5,145.0,67.5,0,0,0.0,3.5,low,1–5

Underdog rows (same games): 206

In [20]:
#finding the amount of points that the underdogs scores based ont he projected team totals 

points_col = "PROJ TEAM TOTAL (CLOSE)"

# make numeric
df[points_col] = pd.to_numeric(df[points_col], errors="coerce")

# Favorite row per game
fav_rows = df[df["CLOSING SPREAD"] < 0].copy()

# Underdog row per game: grab underdog projected total
udog_rows = df[df["CLOSING SPREAD"] > 0][["GAME-ID", points_col]].copy()
udog_rows = udog_rows.rename(columns={points_col: "UDOG_PROJ_TT_CLOSE"})

# One row per game (anchored on favorite) + underdog projected total
games = fav_rows.merge(udog_rows, on="GAME-ID", how="left")

print("Games (favorite rows):", len(games))
print("Missing UDOG_PROJ_TT_CLOSE:", games["UDOG_PROJ_TT_CLOSE"].isna().sum())

games[["GAME-ID", "TEAM", "CLOSING SPREAD", "spread_bucket", "UDOG_PROJ_TT_CLOSE"]].head()

Games (favorite rows): 5761
Missing UDOG_PROJ_TT_CLOSE: 5

,GAME-ID,TEAM,CLOSING SPREAD,spread_bucket,UDOG_PROJ_TT_CLOSE
0,401706962,Kansas Jayhawks,-28.5,10+,64.0
1,401719228,Alabama Crimson Tide,-28.5,10+,67.5
2,401706926,Houston Cougars,-36.5,10+,50.0
3,401706954,Iowa State Cyclones,-46.5,10+,43.5
4,401727062,Gonzaga Bulldogs,-6.5,5–10,75.0

In [21]:
games["udog_points_bucket"] = (
    games.groupby("spread_bucket")["UDOG_PROJ_TT_CLOSE"]
         .transform(lambda s: pd.qcut(s.rank(method="first"), 3, labels=["low","mid","high"]))
)

# Your new 3x3 count table (spread_bucket × underdog proj total bucket)
bucket_counts = (
    games.groupby(["spread_bucket", "udog_points_bucket"])
         .size()
         .unstack(fill_value=0)
)

print(bucket_counts)

udog_points_bucket  low  mid  high
spread_bucket
1–5                 750  749   749
5–10                613  613   613
10+                 557  556   556

In [22]:
ranges = (
    games.groupby(["spread_bucket","udog_points_bucket"])["UDOG_PROJ_TT_CLOSE"]
         .agg(n="count", min_val="min", max_val="max")
)

print(ranges)

                                    n  min_val  max_val
spread_bucket udog_points_bucket
1–5           low                 750    57.25    68.75
              mid                 749    68.75    72.50
              high                749    72.50    88.50
5–10          low                 613    55.00    67.00
              mid                 613    67.00    70.75
              high                613    70.75    86.00
10+           low                 557    43.25    62.25
              mid                 556    62.25    66.75
              high                556    66.75    84.50

In [23]:
ranges = (
    games.groupby(["spread_bucket","udog_points_bucket"])["UDOG_PROJ_TT_CLOSE"]
         .agg(
             n="count",
             min_val="min",
             max_val="max",
             mean_val="mean"
         )
         .round(2)
)

print(ranges)

                                    n  min_val  max_val  mean_val
spread_bucket udog_points_bucket
1–5           low                 750    57.25    68.75     65.98
              mid                 749    68.75    72.50     70.61
              high                749    72.50    88.50     75.74
5–10          low                 613    55.00    67.00     64.29
              mid                 613    67.00    70.75     68.87
              high                613    70.75    86.00     73.71
10+           low                 557    43.25    62.25     58.69
              mid                 556    62.25    66.75     64.55
              high                556    66.75    84.50     70.08

In [25]:
#finding the probabilities again 
games["Team W/L (1/0)"] = pd.to_numeric(games["Team W/L (1/0)"], errors="coerce")
games["Team ML + Opp Team Over Win/Loss (1/0)"] = pd.to_numeric(
    games["Team ML + Opp Team Over Win/Loss (1/0)"], errors="coerce"
)
games["Team Over/Under Proj Team Total (1/0)"] = pd.to_numeric(
    games["Team Over/Under Proj Team Total (1/0)"], errors="coerce"
)
games["Opp Over (1/0)"] = np.where(
    games["Team W/L (1/0)"] == 1,
    games["Team ML + Opp Team Over Win/Loss (1/0)"],
    1 - games["Team Over/Under Proj Team Total (1/0)"]
)

In [26]:
# denominator: favorite wins
fav_wins = (
    games[games["Team W/L (1/0)"] == 1]
    .groupby(["spread_bucket","udog_points_bucket"])
    .size()
)

# numerator: favorite win AND opponent over
joint = (
    games[games["Team ML + Opp Team Over Win/Loss (1/0)"] == 1]
    .groupby(["spread_bucket","udog_points_bucket"])
    .size()
)

p1 = (joint / fav_wins).unstack()

print("P(Underdog Over | Favorite Wins)")
print(p1.round(3))

P(Underdog Over | Favorite Wins)
udog_points_bucket    low    mid   high
spread_bucket
1–5                 0.371  0.332  0.372
5–10                0.369  0.372  0.390
10+                 0.491  0.444  0.443

In [27]:
# denominator: opponent over
opp_over = (
    games[games["Opp Over (1/0)"] == 1]
    .groupby(["spread_bucket","udog_points_bucket"])
    .size()
)

p2 = (joint / opp_over).unstack()

print("\nP(Favorite Wins | Underdog Over)")
print(p2.round(3))

P(Favorite Wins | Underdog Over)
udog_points_bucket    low    mid   high
spread_bucket
1–5                 0.424  0.356  0.428
5–10                0.571  0.616  0.603
10+                 0.915  0.878  0.831

In [32]:
import pandas as pd
import numpy as np

df["CLOSING SPREAD"] = pd.to_numeric(df["CLOSING SPREAD"], errors="coerce")
df["CLOSING TOTAL"]  = pd.to_numeric(df["CLOSING TOTAL"], errors="coerce")

games = (
    df.groupby("GAME-ID", as_index=False)
      .agg(
          SPREAD_ABS=("CLOSING SPREAD", lambda s: np.nanmax(np.abs(s))),
          CLOSING_TOTAL=("CLOSING TOTAL", "first"),
          DATE=("DATE", "first")  # optional
      )
)

print("Unique games:", len(games))
print("Missing CLOSING_TOTAL:", games["CLOSING_TOTAL"].isna().sum())

Unique games: 6294
Missing CLOSING_TOTAL: 526

/var/folders/tk/phxlpd010yl45ky8mgmjkhlc0000gq/T/ipykernel_36256/3435049647.py:10: RuntimeWarning: All-NaN axis encountered
  SPREAD_ABS=("CLOSING SPREAD", lambda s: np.nanmax(np.abs(s))),

In [34]:
games["spread_bucket"] = pd.cut(
    games["SPREAD_ABS"],
    bins=[1, 5, 10, np.inf],
    labels=["1–5", "5–10", "10+"],
    right=False
)

print(games["spread_bucket"].value_counts(dropna=False))

# Quantile cut points
q1, q2 = games["CLOSING_TOTAL"].quantile([1/3, 2/3]).tolist()

# Round to nearest 0.5 for cleaner sportsbook-style numbers
def round_to_half(x):
    return np.round(x * 2) / 2

c1 = float(round_to_half(q1))
c2 = float(round_to_half(q2))

# Ensure strictly increasing (rare edge case if data is very tied)
if c2 <= c1:
    c2 = c1 + 0.5

bins = [-np.inf, c1, c2, np.inf]
labels = [
    f"{c1:.1f} and lower",
    f"{c1:.1f} to {c2:.1f}",
    f"{c2:.1f}+"
]

games["total_points_bucket"] = pd.cut(
    games["CLOSING_TOTAL"],
    bins=bins,
    labels=labels,
    include_lowest=True,
    right=True
)

print("Total-points bin edges used:", bins)
print("Bucket labels:", labels)
print("\nCounts per total_points_bucket:")
print(games["total_points_bucket"].value_counts(dropna=False))

print("\nActual ranges per bucket (min/max):")
print(
    games.groupby("total_points_bucket")["CLOSING_TOTAL"]
         .agg(n="count", min_val="min", max_val="max")
         .round(2)
)

spread_bucket
1–5     2255
5–10    1842
10+     1670
NaN      527
Name: count, dtype: int64
Total-points bin edges used: [-inf, 141.0, 148.5, inf]
Bucket labels: ['141.0 and lower', '141.0 to 148.5', '148.5+']

Counts per total_points_bucket:
total_points_bucket
141.0 to 148.5     2007
141.0 and lower    1938
148.5+             1823
NaN                 526
Name: count, dtype: int64

Actual ranges per bucket (min/max):
                        n  min_val  max_val
total_points_bucket
141.0 and lower      1938    116.5    141.0
141.0 to 148.5       2007    141.5    148.5
148.5+               1823    149.0    181.5

In [35]:
bucket_counts = (
    games.groupby(["spread_bucket", "total_points_bucket"])
         .size()
         .unstack(fill_value=0)
)

print(bucket_counts)

total_points_bucket  141.0 and lower  141.0 to 148.5  148.5+
spread_bucket
1–5                              841             773     641
5–10                             603             651     588
10+                              494             582     594

In [36]:
# Grab favorite rows (spread < 0)
fav_rows = df[df["CLOSING SPREAD"] < 0][[
    "GAME-ID",
    "Team W/L (1/0)",
    "Team Over/Under Proj Team Total (1/0)",
    "Team ML + Opp Team Over Win/Loss (1/0)"
]].copy()

# Merge onto game-level table
games = games.merge(fav_rows, on="GAME-ID", how="left")

# Ensure numeric
games["Team W/L (1/0)"] = pd.to_numeric(games["Team W/L (1/0)"], errors="coerce")
games["Team Over/Under Proj Team Total (1/0)"] = pd.to_numeric(
    games["Team Over/Under Proj Team Total (1/0)"], errors="coerce"
)
games["Team ML + Opp Team Over Win/Loss (1/0)"] = pd.to_numeric(
    games["Team ML + Opp Team Over Win/Loss (1/0)"], errors="coerce"
)

In [37]:
games["Opp Over (1/0)"] = np.where(
    games["Team W/L (1/0)"] == 1,
    games["Team ML + Opp Team Over Win/Loss (1/0)"],
    1 - games["Team Over/Under Proj Team Total (1/0)"]
)
# Denominator: favorite wins
fav_wins = (
    games[games["Team W/L (1/0)"] == 1]
    .groupby(["spread_bucket", "total_points_bucket"])
    .size()
)

# Numerator: favorite win AND opponent over
joint = (
    games[games["Team ML + Opp Team Over Win/Loss (1/0)"] == 1]
    .groupby(["spread_bucket", "total_points_bucket"])
    .size()
)

p1 = (joint / fav_wins).unstack()

print("P(Underdog Over | Favorite Wins)")
print(p1.round(3))

P(Underdog Over | Favorite Wins)
total_points_bucket  141.0 and lower  141.0 to 148.5  148.5+
spread_bucket
1–5                            0.350           0.349   0.379
5–10                           0.380           0.363   0.389
10+                            0.457           0.463   0.459

In [38]:
# Denominator: opponent over
opp_over = (
    games[games["Opp Over (1/0)"] == 1]
    .groupby(["spread_bucket", "total_points_bucket"])
    .size()
)

p2 = (joint / opp_over).unstack()

print("\nP(Favorite Wins | Underdog Over)")
print(p2.round(3))

P(Favorite Wins | Underdog Over)
total_points_bucket  141.0 and lower  141.0 to 148.5  148.5+
spread_bucket
1–5                            0.400           0.385   0.426
5–10                           0.564           0.615   0.610
10+                            0.871           0.867   0.889